In [26]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [27]:
df = pd.DataFrame({
    "soil_moist" : [0.10,0.15,0.20,0.25,0.40,0.60,0.35,0.18,0.45,0.05,0.08,0.27,0.55,0.70,0.12,0.03],
    "temp_c" : [34,30,26,22,28,30,19,22,35,24,33,33,21,25,20,29],
    "sun_hours" : [9,8,7,4,8,10,3,10,12,5,9,11,2,6,1,9],
    "needs_water" : [1,1,1,0,0,0,0,1,0,1,0,1,0,0,1,1]
})

In [28]:
df.head()

   soil_moist  temp_c  sun_hours  needs_water
0        0.10      34          9            1
1        0.15      30          8            1
2        0.20      26          7            1
3        0.25      22          4            0
4        0.40      28          8            0

In [29]:
x = df[['soil_moist',	'temp_c',	'sun_hours']]
y = df['needs_water']

In [30]:
x_min = x.min()
x_max = x.max()
x_scaled = (x-x_min) / (x_max - x_min + 1e-8)

In [31]:
x_scaled.head()

   soil_moist  temp_c  sun_hours
0    0.104478  0.9375   0.727273
1    0.179104  0.6875   0.636364
2    0.253731  0.4375   0.545455
3    0.328358  0.1875   0.272727
4    0.552239  0.5625   0.636364

In [32]:
x_train, x_test, y_train, y_test = train_test_split(
    x_scaled, y,
    test_size=0.25,
    random_state=42
    )

In [33]:
model = keras.Sequential([
    layers.Input(shape = (x_train.shape[1],)),
    layers.Dense(8,activation = 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [34]:
model.compile(optimizer='sgd' , loss='binary_crossentropy' , metrics=['accuracy'])

In [35]:
history = model.fit(
    x_train.values , y_train.values,
    validation_data = (x_test.values,y_test.values),
    epochs = 100,
    batch_size = 4 ,
    verbose = 1
)

Epoch 1/100

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.7500 - loss: 0.6272 - val_accuracy: 0.2500 - val_loss: 0.6726
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7500 - loss: 0.6268 - val_accuracy: 0.2500 - val_loss: 0.6728
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6273 - val_accuracy: 0.2500 - val_loss: 0.6729
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6248 - val_accuracy: 0.2500 - val_loss: 0.6730
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6239 - val_accuracy: 0.2500 - val_loss: 0.6732
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7500 - loss: 0.6240 - val_accuracy: 0.2500 - val_loss: 0.6733
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6225 - val_accuracy: 0.2500 - val_loss: 0.6735
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6223 - val_accuracy: 0.2500 - val_loss: 0.6736
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6212 - val_accuracy: 0.2500 - val_loss: 0.6737
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6207 - val_accuracy: 0.2500 - val_loss: 0.6738
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6198 - val_accuracy: 0.2500 - val_loss: 0.6739
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6194 - val_accuracy: 0.2500 - val_loss: 0.6740
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6192 - val_accuracy: 0.2500 - val_loss: 0.6741
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6184 - val_accuracy: 0.2500 - val_loss: 0.6741
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6172 - val_accuracy: 0.2500 - val_loss: 0.6742
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6173 - val_accuracy: 0.2500 - val_loss: 0.6743
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6158 - val_accuracy: 0.2500 - val_loss: 0.6744
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6151 - val_accuracy: 0.2500 - val_loss: 0.6745
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6152 - val_accuracy: 0.2500 - val_loss: 0.6746
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6138 - val_accuracy: 0.2500 - val_loss: 0.6746
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.6149 - val_accuracy: 0.2500 - val_loss: 0.6747
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6131 - val_accuracy: 0.2500 - val_loss: 0.6748
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6117 - val_accuracy: 0.2500 - val_loss: 0.6748
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6114 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6107 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6093 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6097 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6101 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6074 - val_accuracy: 0.2500 - val_loss: 0.6750
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6078 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6060 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6055 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6051 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6047 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6033 - val_accuracy: 0.2500 - val_loss: 0.6748
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.6025 - val_accuracy: 0.2500 - val_loss: 0.6746
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6030 - val_accuracy: 0.2500 - val_loss: 0.6744
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.6010 - val_accuracy: 0.2500 - val_loss: 0.6744
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6026 - val_accuracy: 0.2500 - val_loss: 0.6744
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5998 - val_accuracy: 0.2500 - val_loss: 0.6743
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5992 - val_accuracy: 0.2500 - val_loss: 0.6743
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5987 - val_accuracy: 0.2500 - val_loss: 0.6742
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5978 - val_accuracy: 0.2500 - val_loss: 0.6742
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5979 - val_accuracy: 0.2500 - val_loss: 0.6742
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5969 - val_accuracy: 0.2500 - val_loss: 0.6741
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5964 - val_accuracy: 0.2500 - val_loss: 0.6740
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5955 - val_accuracy: 0.2500 - val_loss: 0.6739
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5949 - val_accuracy: 0.2500 - val_loss: 0.6738
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5943 - val_accuracy: 0.2500 - val_loss: 0.6737
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5948 - val_accuracy: 0.2500 - val_loss: 0.6736
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5954 - val_accuracy: 0.2500 - val_loss: 0.6735
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7500 - loss: 0.5930 - val_accuracy: 0.2500 - val_loss: 0.6734
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7500 - loss: 0.5921 - val_accuracy: 0.2500 - val_loss: 0.6733
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7500 - loss: 0.5919 - val_accuracy: 0.2500 - val_loss: 0.6732
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7500 - loss: 0.5905 - val_accuracy: 0.2500 - val_loss: 0.6730
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5903 - val_accuracy: 0.2500 - val_loss: 0.6729
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5894 - val_accuracy: 0.2500 - val_loss: 0.6728
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5889 - val_accuracy: 0.2500 - val_loss: 0.6727
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5883 - val_accuracy: 0.2500 - val_loss: 0.6725
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5875 - val_accuracy: 0.2500 - val_loss: 0.6723
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5869 - val_accuracy: 0.2500 - val_loss: 0.6722
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5872 - val_accuracy: 0.2500 - val_loss: 0.6720
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5859 - val_accuracy: 0.2500 - val_loss: 0.6718
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5851 - val_accuracy: 0.2500 - val_loss: 0.6716
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5853 - val_accuracy: 0.2500 - val_loss: 0.6714
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5838 - val_accuracy: 0.2500 - val_loss: 0.6710
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5845 - val_accuracy: 0.2500 - val_loss: 0.6706
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5825 - val_accuracy: 0.2500 - val_loss: 0.6703
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5827 - val_accuracy: 0.2500 - val_loss: 0.6700
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5824 - val_accuracy: 0.2500 - val_loss: 0.6697
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5809 - val_accuracy: 0.2500 - val_loss: 0.6693
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5802 - val_accuracy: 0.2500 - val_loss: 0.6690
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5804 - val_accuracy: 0.2500 - val_loss: 0.6687
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5795 - val_accuracy: 0.2500 - val_loss: 0.6683
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5783 - val_accuracy: 0.2500 - val_loss: 0.6680
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5777 - val_accuracy: 0.2500 - val_loss: 0.6676
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5780 - val_accuracy: 0.2500 - val_loss: 0.6673
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5778 - val_accuracy: 0.2500 - val_loss: 0.6669
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5765 - val_accuracy: 0.2500 - val_loss: 0.6666
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5753 - val_accuracy: 0.2500 - val_loss: 0.6662
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5751 - val_accuracy: 0.2500 - val_loss: 0.6658
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5743 - val_accuracy: 0.2500 - val_loss: 0.6654
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5736 - val_accuracy: 0.2500 - val_loss: 0.6651
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5735 - val_accuracy: 0.2500 - val_loss: 0.6647
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5721 - val_accuracy: 0.2500 - val_loss: 0.6643
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6667 - loss: 0.5735 - val_accuracy: 0.2500 - val_loss: 0.6639
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.5718 - val_accuracy: 0.2500 - val_loss: 0.6635
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5699 - val_accuracy: 0.2500 - val_loss: 0.6631
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5692 - val_accuracy: 0.2500 - val_loss: 0.6627
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5694 - val_accuracy: 0.2500 - val_loss: 0.6624
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5680 - val_accuracy: 0.2500 - val_loss: 0.6619
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.5684 - val_accuracy: 0.2500 - val_loss: 0.6614
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5679 - val_accuracy: 0.2500 - val_loss: 0.6612
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5664 - val_accuracy: 0.2500 - val_loss: 0.6610
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5662 - val_accuracy: 0.5000 - val_loss: 0.6607
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5644 - val_accuracy: 0.5000 - val_loss: 0.6604
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5647 - val_accuracy: 0.5000 - val_loss: 0.6600
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5641 - val_accuracy: 0.5000 - val_loss: 0.6595
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5629 - val_accuracy: 0.5000 - val_loss: 0.6591
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5632 - val_accuracy: 0.5000 - val_loss: 0.6588

# with SGD opti

In [37]:
from tensorflow.keras import optimizers

In [38]:
opt = optimizers.SGD(learning_rate = 0.01 , momentum = 0.9)

In [39]:
model = keras.Sequential([
    layers.Input(shape = (x_train.shape[1],)),
    layers.Dense(8,activation = 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [40]:
model.compile(optimizer= opt , loss='binary_crossentropy' , metrics=['accuracy'])

In [41]:
history = model.fit(
    x_train.values , y_train.values,
    validation_data = (x_test.values,y_test.values),
    epochs = 100,
    batch_size = 4 ,
    verbose = 1
)

Epoch 1/100

3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 101ms/step - accuracy: 0.5000 - loss: 0.7053 - val_accuracy: 0.2500 - val_loss: 0.7318
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.7034 - val_accuracy: 0.2500 - val_loss: 0.7311
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.7019 - val_accuracy: 0.2500 - val_loss: 0.7341
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6977 - val_accuracy: 0.2500 - val_loss: 0.7345
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6950 - val_accuracy: 0.2500 - val_loss: 0.7387
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6913 - val_accuracy: 0.2500 - val_loss: 0.7407
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6896 - val_accuracy: 0.2500 - val_loss: 0.7425
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6854 - val_accuracy: 0.2500 - val_loss: 0.7409
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6823 - val_accuracy: 0.2500 - val_loss: 0.7415
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6784 - val_accuracy: 0.2500 - val_loss: 0.7406
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6759 - val_accuracy: 0.2500 - val_loss: 0.7437
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6717 - val_accuracy: 0.2500 - val_loss: 0.7452
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6684 - val_accuracy: 0.2500 - val_loss: 0.7451
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6650 - val_accuracy: 0.2500 - val_loss: 0.7440
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6621 - val_accuracy: 0.2500 - val_loss: 0.7459
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6578 - val_accuracy: 0.2500 - val_loss: 0.7451
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6518 - val_accuracy: 0.2500 - val_loss: 0.7411
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6481 - val_accuracy: 0.2500 - val_loss: 0.7367
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5833 - loss: 0.6428 - val_accuracy: 0.2500 - val_loss: 0.7324
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6389 - val_accuracy: 0.2500 - val_loss: 0.7323
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6347 - val_accuracy: 0.2500 - val_loss: 0.7299
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6319 - val_accuracy: 0.2500 - val_loss: 0.7251
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6276 - val_accuracy: 0.2500 - val_loss: 0.7226
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6251 - val_accuracy: 0.2500 - val_loss: 0.7185
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5833 - loss: 0.6221 - val_accuracy: 0.2500 - val_loss: 0.7187
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6178 - val_accuracy: 0.2500 - val_loss: 0.7135
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6141 - val_accuracy: 0.2500 - val_loss: 0.7112
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5833 - loss: 0.6107 - val_accuracy: 0.2500 - val_loss: 0.7094
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6093 - val_accuracy: 0.2500 - val_loss: 0.7013
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6039 - val_accuracy: 0.2500 - val_loss: 0.6999
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6667 - loss: 0.6000 - val_accuracy: 0.2500 - val_loss: 0.6955
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.5961 - val_accuracy: 0.2500 - val_loss: 0.6948
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5934 - val_accuracy: 0.2500 - val_loss: 0.6932
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5900 - val_accuracy: 0.2500 - val_loss: 0.6860
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5847 - val_accuracy: 0.2500 - val_loss: 0.6813
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.5816 - val_accuracy: 0.2500 - val_loss: 0.6781
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.5788 - val_accuracy: 0.2500 - val_loss: 0.6777
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.5744 - val_accuracy: 0.5000 - val_loss: 0.6700
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5833 - loss: 0.5702 - val_accuracy: 0.5000 - val_loss: 0.6634
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.5661 - val_accuracy: 0.5000 - val_loss: 0.6616
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7500 - loss: 0.5618 - val_accuracy: 0.5000 - val_loss: 0.6596
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.5585 - val_accuracy: 0.7500 - val_loss: 0.6509
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7500 - loss: 0.5532 - val_accuracy: 0.7500 - val_loss: 0.6468
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5491 - val_accuracy: 0.7500 - val_loss: 0.6435
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7500 - loss: 0.5486 - val_accuracy: 0.7500 - val_loss: 0.6316
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.5410 - val_accuracy: 0.7500 - val_loss: 0.6272
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8333 - loss: 0.5385 - val_accuracy: 0.7500 - val_loss: 0.6274
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8333 - loss: 0.5336 - val_accuracy: 0.7500 - val_loss: 0.6200
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8333 - loss: 0.5292 - val_accuracy: 0.7500 - val_loss: 0.6149
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8333 - loss: 0.5244 - val_accuracy: 0.7500 - val_loss: 0.6096
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.5207 - val_accuracy: 0.7500 - val_loss: 0.6068
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.5163 - val_accuracy: 0.7500 - val_loss: 0.6040
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.5127 - val_accuracy: 0.7500 - val_loss: 0.6027
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5075 - val_accuracy: 0.7500 - val_loss: 0.5999
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8333 - loss: 0.5047 - val_accuracy: 0.7500 - val_loss: 0.5918
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8333 - loss: 0.4997 - val_accuracy: 0.7500 - val_loss: 0.5892
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8333 - loss: 0.4956 - val_accuracy: 0.7500 - val_loss: 0.5869
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.4933 - val_accuracy: 0.7500 - val_loss: 0.5810
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4881 - val_accuracy: 0.7500 - val_loss: 0.5763
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8333 - loss: 0.4841 - val_accuracy: 0.7500 - val_loss: 0.5727
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4807 - val_accuracy: 0.7500 - val_loss: 0.5683
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4764 - val_accuracy: 0.7500 - val_loss: 0.5652
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4729 - val_accuracy: 0.7500 - val_loss: 0.5622
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.4697 - val_accuracy: 0.7500 - val_loss: 0.5586
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4665 - val_accuracy: 0.7500 - val_loss: 0.5624
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.4619 - val_accuracy: 0.7500 - val_loss: 0.5599
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8333 - loss: 0.4591 - val_accuracy: 0.7500 - val_loss: 0.5569
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4562 - val_accuracy: 0.7500 - val_loss: 0.5552
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4520 - val_accuracy: 0.7500 - val_loss: 0.5494
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4494 - val_accuracy: 0.7500 - val_loss: 0.5423
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4457 - val_accuracy: 0.7500 - val_loss: 0.5420
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4430 - val_accuracy: 0.7500 - val_loss: 0.5450
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8333 - loss: 0.4394 - val_accuracy: 0.7500 - val_loss: 0.5438
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.4390 - val_accuracy: 0.7500 - val_loss: 0.5320
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.4345 - val_accuracy: 0.7500 - val_loss: 0.5250
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.4307 - val_accuracy: 0.7500 - val_loss: 0.5263
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.4300 - val_accuracy: 0.7500 - val_loss: 0.5312
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8333 - loss: 0.4247 - val_accuracy: 0.7500 - val_loss: 0.5228
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4251 - val_accuracy: 0.7500 - val_loss: 0.5131
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.4196 - val_accuracy: 0.7500 - val_loss: 0.5142
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4178 - val_accuracy: 0.7500 - val_loss: 0.5136
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.4176 - val_accuracy: 0.7500 - val_loss: 0.5212
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4118 - val_accuracy: 0.7500 - val_loss: 0.5108
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.4090 - val_accuracy: 0.7500 - val_loss: 0.5043
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9167 - loss: 0.4063 - val_accuracy: 0.7500 - val_loss: 0.5040
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4044 - val_accuracy: 0.7500 - val_loss: 0.5054
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.4023 - val_accuracy: 0.7500 - val_loss: 0.5077
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.4008 - val_accuracy: 0.7500 - val_loss: 0.5125
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8333 - loss: 0.3988 - val_accuracy: 0.7500 - val_loss: 0.5129
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.3942 - val_accuracy: 0.7500 - val_loss: 0.5069
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.3951 - val_accuracy: 0.7500 - val_loss: 0.4926
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.3900 - val_accuracy: 0.7500 - val_loss: 0.4909
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.3887 - val_accuracy: 0.7500 - val_loss: 0.4911
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.3866 - val_accuracy: 0.7500 - val_loss: 0.4927
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.9167 - loss: 0.3842 - val_accuracy: 0.7500 - val_loss: 0.4898
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.3826 - val_accuracy: 0.7500 - val_loss: 0.4878
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.3794 - val_accuracy: 0.7500 - val_loss: 0.4907
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.3797 - val_accuracy: 0.7500 - val_loss: 0.4855
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.3776 - val_accuracy: 0.7500 - val_loss: 0.4930
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.3744 - val_accuracy: 0.7500 - val_loss: 0.4887

# accuracy increassed to 91%